services:
  node-app:
    container_name: express-node-app-container
    build: .
    image: express-node-app
    volumes:
      - ./src:/app/src:ro
    ports:
      - "4000:4000"
    env_file:
      - ./.env
